apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  database-name: test
  username: test
  password: test

---

# non-production ready deployment of PostgreSQL
# it's meant only for testing purposes to show the capabilities of the WildFly in the quickstarts
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:9.4
        args: ["-c", "max-prepared-transactions=110", "-c", "log-statement=all"]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgresql
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgresql
        - name: PGDATA
          value: /tmp/mypgdata

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
